version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: genshin-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: genshin-shop

  backend:
    build: ./backend
    container_name: genshin-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/genshin-shop
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_change_this
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: genshin-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: